# Generated by Django 4.2 on 2024-01-15 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enumeration',
            fields=[
                ('enum_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('enum_code', models.CharField(blank=True, max_length=60, null=True)),
                ('sequence_id', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enumeration',
                'ordering': ['-created_stamp'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('is_unread', models.CharField(blank=True, max_length=1, null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'party',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_login_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('salutation', models.CharField(choices=[('Mr.', 'Mr'), ('Mrs', 'Mrs')], max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('bio', models.TextField(null=True)),
                ('initials', models.CharField(max_length=10)),
                ('is_private', models.BooleanField(default=False)),
                ('birth_date', models.DateField(null=True)),
                ('deceased_date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('marrige_date', models.DateField(null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('marital_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.enumeration')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.party')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user_login',
                'ordering': ['-created_stamp'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('status_type_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('has_table', models.CharField(blank=True, max_length=1, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.statustype')),
            ],
            options={
                'db_table': 'status_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatusItem',
            fields=[
                ('status_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status_code', models.CharField(blank=True, max_length=60, null=True)),
                ('sequence_id', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('status_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.statustype')),
            ],
            options={
                'db_table': 'status_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PartyType',
            fields=[
                ('party_type_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('has_table', models.CharField(blank=True, max_length=1, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.partytype')),
            ],
            options={
                'db_table': 'party_type',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='party',
            name='party_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.partytype'),
        ),
        migrations.AddField(
            model_name='party',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.statusitem'),
        ),
        migrations.CreateModel(
            name='EnumerationType',
            fields=[
                ('enum_type_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('has_table', models.CharField(blank=True, max_length=1, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.enumerationtype')),
            ],
            options={
                'db_table': 'enumeration_type',
                'ordering': ['-created_stamp'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='enumeration',
            name='enum_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.enumerationtype'),
        ),
    ]
