# Generated by Django 4.2 on 2024-01-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enumeration',
            options={'managed': True, 'ordering': ['-created_stamp'], 'verbose_name': 'Enumeration'},
        ),
        migrations.AlterModelOptions(
            name='enumerationtype',
            options={'managed': True, 'ordering': ['-created_stamp'], 'verbose_name': 'EnumerationType'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'managed': True, 'verbose_name': 'Party'},
        ),
        migrations.AlterModelOptions(
            name='partytype',
            options={'managed': True, 'verbose_name': 'PartyType'},
        ),
        migrations.AlterModelOptions(
            name='statusitem',
            options={'managed': True, 'verbose_name': 'StatusItem'},
        ),
        migrations.AlterModelOptions(
            name='statustype',
            options={'managed': True, 'verbose_name': 'StatusType'},
        ),
        migrations.AlterModelOptions(
            name='userlogin',
            options={'managed': True, 'ordering': ['-created_stamp'], 'verbose_name': 'UserLogin'},
        ),
    ]
