# Generated by Django 4.2 on 2024-01-15 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_enumeration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enumeration',
            options={'managed': True, 'ordering': ['-created_stamp'], 'verbose_name_plural': 'Enumeration'},
        ),
        migrations.AlterModelOptions(
            name='enumerationtype',
            options={'managed': True, 'ordering': ['-created_stamp'], 'verbose_name_plural': 'EnumerationType'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'managed': True, 'verbose_name_plural': 'Party'},
        ),
        migrations.AlterModelOptions(
            name='partytype',
            options={'managed': True, 'verbose_name_plural': 'PartyType'},
        ),
        migrations.AlterModelOptions(
            name='statusitem',
            options={'managed': True, 'verbose_name_plural': 'StatusItem'},
        ),
        migrations.AlterModelOptions(
            name='statustype',
            options={'managed': True, 'verbose_name_plural': 'StatusType'},
        ),
        migrations.AlterModelOptions(
            name='userlogin',
            options={'managed': True, 'ordering': ['-created_stamp'], 'verbose_name_plural': 'UserLogin'},
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('user_login', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('visit_id', models.CharField(blank=True, max_length=20, null=True)),
                ('from_date', models.DateTimeField()),
                ('thru_date', models.DateTimeField(blank=True, null=True)),
                ('password_used', models.CharField(blank=True, max_length=255, null=True)),
                ('successful_login', models.CharField(blank=True, max_length=1, null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.party')),
            ],
            options={
                'verbose_name_plural': 'UserLoginHistory',
                'db_table': 'user_login_history',
                'managed': True,
                'unique_together': {('user_login', 'from_date')},
            },
        ),
    ]
