# Generated by Django 4.2 on 2024-01-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_enumeration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='from_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
