# Generated by Django 4.2 on 2024-01-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_userlogin_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginHistory',
        ),
    ]
