# Generated by Django 4.2 on 2024-01-16 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_userloginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginhistory',
            name='user_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
