# Generated by Django 4.2 on 2024-01-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_userloginhistory_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='Users.enumeration'),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='marital_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marital_status', to='Users.enumeration'),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='salutation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salutation', to='Users.enumeration'),
        ),
    ]
