# Generated by Django 4.2 on 2024-01-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_userlogin_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='party',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.party'),
        ),
    ]
