# Generated by Django 4.2 on 2024-01-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_contactmech_contact_mech_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmech',
            name='contact_mech_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
