# Generated by Django 4.2 on 2024-01-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_contactmech_contact_mech_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
