# Generated by Django 4.2 on 2024-01-22 15:09

import Helpers.Utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_alter_content_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmechpurposetype',
            name='contact_mech_purpose_type_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contactmechtype',
            name='contact_mech_type_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentassoc',
            name='content_assoc_id',
            field=models.CharField(default=Helpers.Utils.gen_content_assoc, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentassoctype',
            name='content_assoc_type_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentpurposetype',
            name='content_purpose_type_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='content_type_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataresource',
            name='data_resource_id',
            field=models.CharField(default=Helpers.Utils.gen_data_resource, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataresourcetype',
            name='data_resource_type_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enumeration',
            name='enum_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enumerationtype',
            name='enum_type_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geo',
            name='geo_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geoassoc',
            name='geo_assoc_id',
            field=models.CharField(default=Helpers.Utils.gen_geo_assoc, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geoassoctype',
            name='geo_assoc_type_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geotype',
            name='geo_type_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partycontactmech',
            name='pcm_id',
            field=models.CharField(default=Helpers.Utils.generate_pcm, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='partycontactmechpurpose',
            name='pcm_purpose_id',
            field=models.CharField(default=Helpers.Utils.generate_pcm_porpuse, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='partycontent',
            name='party_content_id',
            field=models.CharField(default=Helpers.Utils.gen_party_content, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='partycontenttype',
            name='party_content_type_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partytype',
            name='party_type_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statusitem',
            name='status_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='status_type_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='user_login_id',
            field=models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='ulh_id',
            field=models.CharField(default=Helpers.Utils.gen_user_login_history, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
