# Generated by Django 4.2 on 2024-01-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_alter_contactmechpurposetype_contact_mech_purpose_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataresource',
            name='object_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
