# Generated by Django 4.2 on 2024-01-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_alter_dataresource_object_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partycontent',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.party'),
        ),
    ]
