# Generated by Django 4.2 on 2024-01-24 06:20

import Helpers.Utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_alter_partycontent_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyClassificationType',
            fields=[
                ('party_classification_type_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('has_table', models.CharField(blank=True, max_length=1, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.partyclassificationtype')),
            ],
            options={
                'db_table': 'party_classification_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PartyClassificationGroup',
            fields=[
                ('party_classification_group_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.partyclassificationgroup')),
                ('party_classification_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.partyclassificationtype')),
            ],
            options={
                'db_table': 'party_classification_group',
                'managed': True,
                'unique_together': {('party_classification_group_id', 'party_classification_type')},
            },
        ),
        migrations.CreateModel(
            name='PartyClassification',
            fields=[
                ('party_classification_id', models.CharField(default=Helpers.Utils.gen_party_classification, max_length=40, primary_key=True, serialize=False)),
                ('from_date', models.DateTimeField(auto_now_add=True)),
                ('thru_date', models.DateTimeField(blank=True, null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.party')),
                ('party_classification_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.partyclassificationgroup')),
            ],
            options={
                'db_table': 'party_classification',
                'managed': True,
                'unique_together': {('party', 'party_classification_group', 'from_date')},
            },
        ),
    ]
