# Generated by Django 4.2 on 2024-01-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_partyclassificationtype_partyclassificationgroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partyclassification',
            options={'managed': True, 'verbose_name_plural': 'PartyClassification'},
        ),
        migrations.AlterModelOptions(
            name='partyclassificationgroup',
            options={'managed': True, 'verbose_name_plural': 'PartyClassificationGroup'},
        ),
        migrations.AlterModelOptions(
            name='partyclassificationtype',
            options={'managed': True, 'verbose_name_plural': 'PartyClassificationType'},
        ),
    ]
