# Generated by Django 4.2 on 2024-01-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_alter_partyclassification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
