# Generated by Django 4.2 on 2024-01-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_userlogin_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
