# Generated by Django 4.2 on 2024-01-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_alter_userlogin_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partycontactmech',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='partycontactmech',
            name='cm_purpose_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.contactmechpurposetype'),
        ),
        migrations.AlterUniqueTogether(
            name='partycontactmech',
            unique_together={('party', 'contact_mech', 'cm_purpose_type', 'from_date')},
        ),
        migrations.DeleteModel(
            name='PartyContactMechPurpose',
        ),
    ]
