# Generated by Django 4.2 on 2024-01-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_alter_partycontactmech_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partyclassificationgroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='partyclassificationgroup',
            name='parent_group',
        ),
        migrations.RemoveField(
            model_name='partyclassificationgroup',
            name='party_classification_type',
        ),
        migrations.RemoveField(
            model_name='partyclassificationtype',
            name='parent_type',
        ),
        migrations.DeleteModel(
            name='PartyClassification',
        ),
        migrations.DeleteModel(
            name='PartyClassificationGroup',
        ),
        migrations.DeleteModel(
            name='PartyClassificationType',
        ),
    ]
