# Generated by Django 4.2 on 2024-01-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_alter_partyclassificationgroup_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('role_type_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('has_table', models.CharField(blank=True, max_length=1, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.roletype')),
            ],
            options={
                'verbose_name_plural': 'RoleType',
                'db_table': 'role_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('party_role_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.party')),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.roletype')),
            ],
            options={
                'verbose_name_plural': 'PartyRole',
                'db_table': 'party_role',
                'managed': True,
                'unique_together': {('party', 'role_type')},
            },
        ),
        migrations.CreateModel(
            name='PartyRelationshipType',
            fields=[
                ('party_relationship_type_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('has_table', models.CharField(blank=True, max_length=1, null=True)),
                ('party_relationship_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.partyrelationshiptype')),
                ('role_type_id_valid_from', models.ForeignKey(blank=True, db_column='role_type_id_valid_from', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.roletype')),
                ('role_type_id_valid_to', models.ForeignKey(blank=True, db_column='role_type_id_valid_to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partyrelationshiptype_role_type_id_valid_to_set', to='Users.roletype')),
            ],
            options={
                'verbose_name_plural': 'PartyRelationshipType',
                'db_table': 'party_relationship_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PartyRelationship',
            fields=[
                ('party_relationship_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('relationship_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position_title', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateTimeField(auto_now_add=True)),
                ('thru_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('party_relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.partyrelationshiptype')),
                ('party_role_from', models.ForeignKey(db_column='party_role_from', on_delete=django.db.models.deletion.DO_NOTHING, related_name='partyrelationship_party_role_from_set', to='Users.partyrole')),
                ('party_role_to', models.ForeignKey(db_column='party_role_to', on_delete=django.db.models.deletion.DO_NOTHING, related_name='partyrelationship_party_role_to_set', to='Users.partyrole')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.statusitem')),
            ],
            options={
                'verbose_name_plural': 'PartyRelationship',
                'db_table': 'party_relationship',
                'managed': True,
                'unique_together': {('party_role_from', 'party_role_to', 'party_relationship_type', 'from_date')},
            },
        ),
    ]
