# Generated by Django 4.2 on 2024-01-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_roletype_partyrole_partyrelationshiptype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roletype',
            name='role_type_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
