# Generated by Django 4.2 on 2024-01-26 03:57

import Helpers.Utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_alter_roletype_role_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyrelationship',
            name='relationship_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partyrole',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.party'),
        ),
        migrations.AlterField(
            model_name='partyrole',
            name='party_role_id',
            field=models.CharField(default=Helpers.Utils.gen_party_role, max_length=40, primary_key=True, serialize=False),
        ),
    ]
