# Generated by Django 5.1 on 2024-09-02 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_alter_content_options_alter_contentassoc_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginFCM',
            fields=[
                ('ulf_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('fcm_key', models.TextField(blank=True, null=True)),
                ('from_date', models.DateTimeField(auto_now_add=True)),
                ('thru_date', models.DateTimeField(auto_now_add=True)),
                ('updated_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_stamp', models.DateTimeField(auto_now_add=True)),
                ('user_login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserLoginFCM',
                'db_table': 'user_login_fcms',
                'ordering': ['-created_stamp'],
                'managed': True,
            },
        ),
    ]
