# Generated by Django 5.1 on 2024-09-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_userloginfcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginfcm',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.enumeration'),
        ),
        migrations.AddField(
            model_name='userloginfcm',
            name='fcm_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userloginfcm',
            name='thru_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
