# Generated by Django 4.2.16 on 2024-11-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0029_alter_contactmech_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='external_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
